### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by aspidites** [ajnsit/concur#7]
I didn't see any install instructions, but have come up with (I think) a minimal `stack.yaml` configuration:

```yaml
resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

packages:
- location: .

- location:
    git: https://github.com/ajnsit/concur
    commit: 83cf5e31d8de6f32014bb7c5becfe98683053a5e
  extra-dep: true
  subdirs:
    - concur-vdom
    - concur-core
- location:
    git: https://github.com/ghcjs/ghcjs-ffiqq
    commit: b52338c2dcd3b0707bc8aff2e171411614d4aedb
  extra-dep: true

- location:
    git: https://github.com/ajnsit/ghcjs-vdom
    commit: c9a72e5d6a2556900bfea96e3078adfc89aba858
  extra-dep: true

extra-deps:
  - natural-transformation-0.4
  - ghcjs-dom-0.9.2.0
  - ghcjs-vdom-0.2.0.0
  - ghcjs-ffiqq-0.1.0.0
  - ghcjs-dom-jsffi-0.9.2.0

flags: {}

extra-package-dbs: []

```
With the above, I can compile a project (and apparently concur examples) with `stack setup && stack build), assuming I've already added `concur-core`, `concur-vdom`, and `ghcjs-vdom` to `build-depends`.

I'm currently building after having added the dependencies for `ghcjs-ffiqq`, so I'll update this if needed once that's done, or ask for help if I struggle. I'm not submitting a PR because I wasn't sure where/if you wanted this. Easiest thing I can think to do is add appropriate `stack.yaml` files to the examples directory of each backend directory and then briefly hint at them in concur's readme.
